# Generated by Django 6.1.1 on 2026-09-09 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20)),
                ('recurrence_type', models.CharField(choices=[('one_off', 'One-off'), ('recurring', 'Recurring')], default='one_off', max_length=20)),
                ('recurrence_interval', models.PositiveIntegerField(blank=True, help_text='Days between recurrences (recurring chores only)', null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('time_estimate', models.CharField(choices=[('quick', 'Quick'), ('medium', 'Medium'), ('big', 'Big')], max_length=10)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('last_completed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_chores', to='chores.householdmember')),
            ],
        ),
    ]
